### PR TITLE
update of notifications (tap, button, pin, image, delete listeners)

### PR DESCRIPTION
**Pull request by zfxstd**
Just small update, which adds some useful methods to notifications. Docs and version updated too.

### CODE REVIEW

**Comment by roccomuso** [comment]
Can you paste screenshot of button1,2,3 usage?

**Comment by zfxstd** [comment]
Yes, please. 
For now there is no way to direct communication between node and termux, termux supports only shell actions. But i want to create package which something like events with callbacks. This would be very useful.

image
image
image

**Comment by roccomuso** [comment]
thanks!
ok

**Comment by roccomuso** [comment]
I'm gonna release also a new version

**Comment by zfxstd** [comment]
Thank you too!

**Pull request merged**
